const Sequelize = require('sequelize');
const { MessageEmbed } = require('discord.js');

const sequelize = new Sequelize('database', 'user', 'password', {
    host: 'localhost',
    dialect: 'sqlite',
    logging: false,
    // SQLite only
    storage: 'database.sqlite',
});

const warAttendance = sequelize.define('warattendance', {
    id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        primaryKey: true
    },
    characterName: Sequelize.STRING,
    activityStatus: Sequelize.STRING,
    warDate: Sequelize.DATEONLY,
    logKey: Sequelize.STRING,
    
});

module.exports = {
    config: {
        name: 'online',
        description: 'Get all offline members with specific attendance ID',
        usage: `!online`,
    },
    async run (bot,message,args) {
        
        if( args.length == 0 ){
            message.reply('Enter an ID  <:bakbaka:991353414124576849>');
            return false;
        } else if (args[0].length == 8) {
            
            const guildMember = await warAttendance.findAll({ where: { logKey: args, activityStatus: 'Online'} });
            
            if(guildMember.length != 0){
                
                let onlineMembers = '\n';
                let onlineMembersPart2 = '\n';
                let onlineMembersPart3 = '\n';
                let count = 1;
                let warDate = '';
                
                const onlineMemberRecord = new MessageEmbed()
                .setThumbnail('https://i.imgur.com/znbc6kX.png')
                .setTimestamp()
                .setFooter({ text: 'Generated by ' + message.member.displayName, iconURL: 'https://i.imgur.com/RQiFqr7.gif' })
                .setColor('RANDOM');
                
                for( const member of guildMember ){
                    
                    if(onlineMembers.length < 1000 ){
                        onlineMembers += count + '. ' + member.characterName + '\n';
                    } else {
                        
                        if(onlineMembersPart2.length < 1000 ){
                            onlineMembersPart2 += count + '. ' + member.characterName + '\n';
                        } else {
                            onlineMembersPart3 += count + '. ' + member.characterName + '\n';
                        }
                        
                    }
                    
                    warDate = member.warDate;
                    count++;
                }
                
                onlineMemberRecord.setTitle('Supremacy • War Attendance Record');
                onlineMemberRecord.addField('Guild War • ' + warDate + '\n\nOnline Member List', onlineMembers);
                
                if(onlineMembers.length > 1000 ){
                    onlineMemberRecord.addField('Continuation...', onlineMembersPart2);
                }
                
                if(onlineMembersPart2.length > 1000 ){
                    onlineMemberRecord.addField('And some more...', onlineMembersPart3);
                } 
                
                message.channel.send({ embeds: [onlineMemberRecord] });
                
            } else {

                message.reply('It seems that you have entered an invalid ID  <:bakbaka:991353414124576849>');

            }
            
        } else {
            
            message.reply('It seems that you have entered an invalid ID  <:bakbaka:991353414124576849>');
            
        }
        
    }
}