const { MessageEmbed } = require('discord.js');

module.exports = {
    config: {
        name: 'party',
        description: 'Get current guild member\'s party list',
        usage: `!party`,
    },
    async run (bot,message,args) {
        
        try {     
            
            let member1 = message.mentions.members.first() || message.member,
            
            user = member1.user;
            
            let userRoles = member1.roles.cache.map(r => r.name);
            
            let guildDivisions = [
                'THOR - 1',
                'THOR - 2',
                'THOR - 3',
                'THOR - 4',
                'THOR - 5',
                'THOR - 6',
                'THOR - 7',
                'THOR - 8',
                'THOR - 9',
                'HERA - 1',
                'HERA - 2',
                'HERA - 3',
                'HERA - 4',
                'EGIL - 1',
                'EGIL - 2',
                'LOKI - 1',
                'LOKI - 2',
                'ASTA - 1',
                'ASTA - 2'
                
            ];
            
            const divisionName = userRoles.filter(r=> guildDivisions.includes(r));
            
            if( divisionName.length === 0 ){
                
                const party_list = new MessageEmbed()
                .setTitle('Paradox • Party List')
                .setThumbnail('https://i.imgur.com/kJWUdAs.png')
                .setDescription('You are currently not assigned to any party')
                .setImage('https://i.imgur.com/m0IweDf.jpg')
                .setColor('RANDOM');

                if(message.channel.id === '991264527666655283'){
                    
                    message.channel.send({ embeds: [party_list] });
                    
                } else {
                    
                    if( bot.channels.cache.get('991264527666655283').send(`Here is your party list ${message.author}!`)){

                        bot.channels.cache.get('991264527666655283').send({ embeds: [party_list] });

                        setTimeout(function(){
                            message.reply(`Hey ${message.author}, this command is not allowed here. I have posted your party list on <#991264527666655283>. `);
                            message.channel.send('https://i.imgur.com/4JAp8I3.gif');
                        }, 1000);
                        
                    }
                    
                }
                
            } else {
                
                let member_counter = 1;
                let total_members = '\n';
                let partyLeader = '';
                const list = bot.guilds.cache.get(message.guild.id);
                
                for (const member of list.members.cache) {
                    
                    if(member[1].roles.cache.map(r => r.name).includes(divisionName[0])){
                        total_members = total_members + '' + member_counter + '. ' + member[1].displayName + '\n';
                        member_counter++;
                        
                        //check if the member is a party leader
                        if(member[1].roles.cache.map(r => r.name).includes('Party Leader')){
                            partyLeader =  member[1].displayName;        
                        }
                    }
                    
                }
                
                const party_list = new MessageEmbed()
                .setTitle('Paradox • Party List')
                .setThumbnail('https://i.imgur.com/kJWUdAs.png')
                .addField('Division', divisionName[0], false)
                .addField('Party Members', total_members, true)
                .addField('\u200B', '\u200B', true)
                .addField('Party Leader', partyLeader, true)
                .setColor('RANDOM')
                .setFooter({ text: 'Generated by ' + message.member.displayName + ' • Always remember your division names', iconURL: 'https://i.imgur.com/RQiFqr7.gif' });
                
                if(divisionName[0].includes('THOR')){
                    party_list.setImage('https://i.imgur.com/cdAIrxL.gif');
                } else if(divisionName[0].includes('HERA')){
                    party_list.setImage('https://i.imgur.com/62TRdsZ.gif');
                } else if(divisionName[0].includes('EGIL')){
                    party_list.setImage('https://i.imgur.com/rKDChHd.gif');
                } else if(divisionName[0].includes('LOKI')){
                    party_list.setImage('https://i.imgur.com/kR0VWGc.gif');
                } else if(divisionName[0].includes('ASTA')){
                    party_list.setImage('https://i.imgur.com/zmd0uQX.gif');
                }
                
                if(message.channel.id === '991264527666655283'){
                    
                    message.channel.send({ embeds: [party_list] });
                    
                } else {
                    
                    if( bot.channels.cache.get('991264527666655283').send(`Here is your party list ${message.author}!`)){

                        bot.channels.cache.get('991264527666655283').send({ embeds: [party_list] });

                        setTimeout(function(){
                            message.reply(`Hey ${message.author}, this command is not allowed here. I have posted your party list on <#991264527666655283>. `);
                            message.channel.send('https://i.imgur.com/4JAp8I3.gif');
                        }, 1000);
                        
                    }
                    
                }

            }
            
        } catch (error) {
            console.log(error);
        }
        
        
    }
}